name: akamai-property
on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
jobs:
  get-affected-stacks:
    uses: ./.github/workflows/ci-atmos-affected-stacks.yaml

  build-matrix:
    needs: get-affected-stacks
    runs-on: ubuntu-latest
    steps:
      - run: |
          matrix=echo '${{ needs.get-affected-stacks.outputs.affected }}'' | jq -c '{include:[.[] | select(.component_path=="components/terraform/base-property"]}'
          echo "matrix=$matrix" >> $GITHUB_OUTPUT
          echo $matrix
