name: akamai-property-draft
run-name: Akamai Property Build Rule Tree
on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
jobs:
  get-affected-stacks:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.affected.outputs.matrix }}
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2
      - uses: cloudposse/github-action-setup-atmos@v1.0.0
      - id: affected
        uses: cloudposse/github-action-atmos-affected-stacks@feature/initial-implementation

  # Create a "draft" deployment environment for each stack in the matrix. This environment will be auto-deployed to
  # without approvals. This is to allow the PR to be tested by applying the changes to Akamai to build the rule tree
  # but not activating it.
  prep-draft-deployment-env:
    needs: get-affected-stacks
    strategy:
      matrix: ${{ fromJson(needs.affected.outputs.matrix) }}
    uses: ./.github/workflows/ci-atmos-create-update-deployment-env.yaml
    if: ${{ matrix.component_path=="components/terraform/base-property" }}
    with:
      auto-deploy: true
      ref: ${{ github.event.pull_request.head.sha }}
      default-branch: ${{ github.event.repository.default_branch }}
      stack: ${{ matrix.stack }}
      component: ${{ matrix.component }}
      full_stack_name: ${{ matrix.full_stack_name }}-draft
    secrets:
      environments_github_token: ${{ secrets.DEPLOYMENTS_GITHUB_TOKEN }}

  # Plan and apply the changes to the draft environment
  plan-apply:
    name: ${{ matrix.stack }}-${{ matrix.component }}
    needs:
      - get-affected-stacks
      - prep-draft-deployment-env
    strategy:
      matrix: ${{ fromJson(needs.affected.outputs.matrix) }}
    uses: ./.github/workflows/ci-atmos-plan-and-apply.yaml
    if: ${{ matrix.component_path=="components/terraform/base-property" }}
    with:
      ref: ${{ github.event.pull_request.head.sha }}
      default-branch: ${{ github.event.repository.default_branch }}
      stack: ${{ matrix.stack }}
      component: ${{ matrix.component }}
      component_path: ${{ matrix.component_path }}
      environment: ${{ matrix.full_stack_name }}-draft
    secrets:
      environments_github_token: ${{ secrets.DEPLOYMENTS_GITHUB_TOKEN }}
