name: akamai-property-draft
run-name: Akamai Property Activation
on:
  workflow_dispatch:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  # Get a list of all stacks that have been affected by the PR
  get-affected-stacks:
    uses: ./.github/workflows/ci-atmos-affected-stacks.yaml
    with:
      head-ref: HEAD~1

  # Build a matrix of stacks that have been affected by the PR. Only include the stacks that are an instance of
  # base-property
  build-matrix:
    needs: get-affected-stacks
    if: ${{ needs.get-affected-stacks.outputs.has-affected-stacks == 'true' }}
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.matrix.outputs.matrix }}
      has-changes: ${{ steps.matrix.outputs.matrix!='{"include":[]}'}}
    steps:
      - id: matrix
        run: |
          matrix=$(echo ${{ needs.get-affected-stacks.outputs.affected }} | jq -c '{include:[.[] | select(.component_path=="components/terraform/base-property")]}')
          echo "matrix=$matrix" >> $GITHUB_OUTPUT

  # Plan and apply the changes
  plan-apply:
    if: ${{ needs.build-matrix.outputs.has-changes == 'true' }}
    name: ${{ matrix.stack }}-${{ matrix.component }}
    needs:
      - build-matrix
    strategy:
      matrix: ${{ fromJson(needs.build-matrix.outputs.matrix) }}
    uses: ./.github/workflows/ci-atmos-plan-and-apply.yaml
    with:
      ref: ${{ github.event.pull_request.head.sha }}
      default-branch: ${{ github.event.repository.default_branch }}
      stack: ${{ matrix.stack }}
      component: ${{ matrix.component }}
      component_path: ${{ matrix.component_path }}
      environment: ${{ matrix.full_stack_name }}

  dependencies-level-1:
    if: ${{ needs.plan-apply.outputs.has-dependencies == 'true' }}
    name: ${{ matrix.stack }}-${{ matrix.component }}
    needs:
      - plan-apply
    strategy:
      matrix: ${{ fromJson(needs.plan-apply.outputs.dependencies) }}
    uses: ./.github/workflows/ci-atmos-plan-and-apply.yaml
    with:
      ref: ${{ github.event.pull_request.head.sha }}
      default-branch: ${{ github.event.repository.default_branch }}
      stack: ${{ matrix.stack }}
      component: ${{ matrix.component }}
      component_path: ${{ matrix.component_path }}
      environment: ${{ matrix.full_stack_name }}

  dependencies-level-2:
    if: ${{ needs.dependencies-level-1.outputs.has-dependencies == 'true' }}
    name: ${{ matrix.stack }}-${{ matrix.component }}
    needs:
      - dependencies-level-1
    strategy:
      matrix: ${{ fromJson(needs.dependencies-level-1.outputs.dependencies) }}
    uses: ./.github/workflows/ci-atmos-plan-and-apply.yaml
    with:
      ref: ${{ github.event.pull_request.head.sha }}
      default-branch: ${{ github.event.repository.default_branch }}
      stack: ${{ matrix.stack }}
      component: ${{ matrix.component }}
      component_path: ${{ matrix.component_path }}
      environment: ${{ matrix.full_stack_name }}

  dependencies-level-3:
    if: ${{ needs.dependencies-level-2.outputs.has-dependencies == 'true' }}
    name: ${{ matrix.stack }}-${{ matrix.component }}
    needs:
      - dependencies-level-2
    strategy:
      matrix: ${{ fromJson(needs.dependencies-level-2.outputs.dependencies) }}
    uses: ./.github/workflows/ci-atmos-plan-and-apply.yaml
    with:
      ref: ${{ github.event.pull_request.head.sha }}
      default-branch: ${{ github.event.repository.default_branch }}
      stack: ${{ matrix.stack }}
      component: ${{ matrix.component }}
      component_path: ${{ matrix.component_path }}
      environment: ${{ matrix.full_stack_name }}
