name: akamai-property
on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
jobs:
  get-affected-stacks:
    uses: ./.github/workflows/ci-atmos-affected-stacks.yaml

  build-matrix:
    needs: get-affected-stacks
    if: ${{ needs.get-affected-stacks.outputs.has-affected-stacks == 'true' }}
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.matrix.outputs.matrix }}
    steps:
      - id: matrix
        run: |
          matrix=$(echo ${{ needs.get-affected-stacks.outputs.affected }} | jq -c '{include:[.[] | select(.component_path=="components/terraform/base-property")]}')
          echo "$matrix"
          echo "matrix='$matrix'" >> $GITHUB_OUTPUT
          echo "$GITHUB_OUTPUT"
          cat "$GITHUB_OUTPUT"

  test:
    needs: build-matrix
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo ${{ needs.build-matrix.outputs.matrix }}

  # test2:
  #   needs: build-matrix
  #   strategy:
  #     matrix: ${{fromJson('{"include":[{"stack":"akadev-corp-eng","component":"www","component_path":"components/terraform/base-property","full_stack_name":"akadev-corp-eng-www"}]}')}}
  #   runs-on: ubuntu-latest
  #   steps:
  #     - run: |
  #         echo ${{ matrix.stack }}

  # prep-deployment-env:
  #   needs: build-matrix
  #   strategy:
  #     matrix: ${{ fromJson(needs.build-matrix.outputs.matrix) }}
  #   uses: ./.github/workflows/ci-atmos-create-update-deployment-env.yaml
  #   with:
  #     ref: ${{ github.event.pull_request.head.sha }}
  #     default-branch: ${{ github.event.repository.default_branch }}
  #     stack: ${{ matrix.stack }}
  #     component: ${{ matrix.component }}
  #     full_stack_name: ${{ matrix.full_stack_name }}
  #     github_token: ${{ github.GITHUB_TOKEN }}

  # plan-apply:
  #   needs: prep-deployment-env
  #   strategy:
  #     matrix: ${{fromJson(needs.build-matrix.outputs.matrix)}}
  #   uses: ./.github/workflows/ci-atmos-plan-and-apply.yaml
  #   with:
  #     ref: ${{ github.event.pull_request.head.sha }}
  #     default-branch: ${{ github.event.repository.default_branch }}
  #     stack: ${{ matrix.stack }}
  #     component: ${{ matrix.component }}
  #     component_path: ${{ matrix.component_path }}
  #     environment: ${{ matrix.full_stack_name }}-draft
