name: akamai-property-draft
run-name: Akamai Property Activation
on:
  workflow_dispatch:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  # Get a list of all stacks that have been affected by the PR
  get-affected-stacks:
    uses: ./.github/workflows/ci-atmos-affected-stacks.yaml
    with:
      head-ref: HEAD~1
