name: ci-atmos-plan-and-apply
on:
  workflow_call:
    inputs:
      ref:
        description: The ref to checkout. If not provided, the pull_request head ref is used.
        required: false
        type: string
        default: ${{ github.event.pull_request.head.sha }}
      default-branch:
        description: The default branch to use for the base ref.
        required: false
        type: string
        default: ${{ github.event.repository.default_branch }}
      stack:
        description: The stack name.
        required: true
        type: string
      component:
        description: The component name.
        required: true
        type: string
      component_path:
        description: The component path.
        required: true
        type: string
      environment:
        description: The GitHub environment name to deploy to.
        required: true
        type: string
    outputs:
      dependencies:
        description: The dependencies matrix
        value: ${{ jobs.dependencies-matrix.outputs.matrix }}
      has-dependencies:
        value: ${{ jobs.dependencies-matrix.outputs.has-dependencies }}
jobs:
  plan:
    runs-on: ubuntu-latest
    steps:
      - run: echo "atmos terraform plan ${{inputs.component}} -s ${{inputs.stack}}"
  apply:
    runs-on: ubuntu-latest
    needs: plan
    environment: ${{ inputs.environment }}
    steps:
      - run: echo "atmos terraform apply ${{inputs.component}} -s ${{inputs.stack}}"
  dependencies-matrix:
    runs-on: ubuntu-latest
    needs:
      - apply
    outputs:
      matrix: ${{ steps.matrix.outputs.matrix }}
      has-dependencies: ${{ steps.matrix.outputs.matrix!='{"include":[]}'}}
    steps:
      - run: |
          # This is a mock of what the atmos describe dependants command will do
          if [[ "${{inputs.stack}}-${{inputs.component}}" == "akadev-corp-eng-www" ]]; then
          dependencies<<EOF
            [
              {
                  "component": "www-activation",
                  "stack": "akadev-corp-eng",
                  "component_path": "components/terraform/base-property",
                  "full_stack_name": "akadev-corp-eng-www-activation"
              }
            ]
          EOF
          elif [[ "${{inputs.stack}}-${{inputs.component}}" == "akadev-corp-prod-www" ]]; then
          dependencies<<EOF
            [
              {
                  "component": "www-activation",
                  "stack": "akadev-corp-prod",
                  "component_path": "components/terraform/base-property",
                  "full_stack_name": "akadev-corp-prod-www-activation"
              }
            ]
          EOF
          elif [[ "${{inputs.stack}}-${{inputs.component}}" == "akadev-corp-eng-www-activation" ]]; then
          dependencies<<EOF
            [
              {
                  "component": "devdatastream",
                  "stack": "akadev-corp-eng",
                  "component_path": "components/terraform/datastream",
                  "full_stack_name": "akadev-corp-eng-devdatastream"
              }
            ]
          EOF
          elif [[ "${{inputs.stack}}-${{inputs.component}}" == "akadev-corp-prod-www-activation" ]]; then
          dependencies<<EOF
            [
              {
                  "component": "devdatastream",
                  "stack": "akadev-corp-eng",
                  "component_path": "components/terraform/datastream",
                  "full_stack_name": "akadev-corp-prod-prddatastream"
              }
            ]
          EOF
          elif [[ "${{inputs.stack}}-${{inputs.component}}" == "akadev-corp-eng-devdatastream" ]]; then
          dependencies<<EOF
            [
              {
                  "component": "devdatastream-activation",
                  "component_path": "components/terraform/datastream-aactivation",
                  "stack": "akadev-corp-eng",
                  "full_stack_name": "akadev-corp-eng-devdatastream-activation"
              }
            ]
          EOF
          elif [[ "${{inputs.stack}}-${{inputs.component}}" == "akadev-corp-prod-proddatastream" ]]; then
          dependencies<<EOF
            [
              {
                  "component": "proddatastream-activation",
                  "component_path": "components/terraform/datastream-activation",
                  "stack": "akadev-corp-prod",
                  "full_stack_name": "akadev-corp-prod-proddatastream-activation"
              }
            ]
          EOF
          elif [[ "${{inputs.stack}}-${{inputs.component}}" == "akadev-corp-eng-devdatastream-activation" ]]; then
          dependencies<<EOF
            [
              {
                  "component": "www",
                  "component_path": "components/terraform/base-property",
                  "stack": "akadev-corp-eng",
                  "full_stack_name": "akadev-corp-eng-www"
              }
            ]
          EOF
          elif [[ "${{inputs.stack}}-${{inputs.component}}" == "akadev-corp-prod-proddatastream-activation" ]]; then
          dependencies<<EOF
            [
              {
                  "component": "www",
                  "component_path": "components/terraform/base-property",
                  "stack": "akadev-corp-prod",
                  "full_stack_name": "akadev-corp-prod-www"
              }
            ]
          EOF
          else
            echo "Invalid parameter: ${{inputs.stack}}-${{inputs.component}}"
            exit 1
          fi
          matrix=$(echo "$dependencies" | jq -c '{include:[.[]]}')
          echo "matrix=$matrix" >> $GITHUB_OUTPUT
