name: ci-atmos-plan-and-apply
on:
  workflow_call:
    inputs:
      ref:
        description: The ref to checkout. If not provided, the pull_request head ref is used.
        required: false
        type: string
        default: ${{ github.event.pull_request.head.sha }}
      default-branch:
        description: The default branch to use for the base ref.
        required: false
        type: string
        default: ${{ github.event.repository.default_branch }}
      stack:
        description: The stack name.
        required: true
        type: string
      component:
        description: The component name.
        required: true
        type: string
      component_path:
        description: The component path.
        required: true
        type: string
      environment:
        description: The GitHub environment name to deploy to.
        required: true
        type: string
    outputs:
      dependencies:
        description: The dependencies matrix
        value: ${{ jobs.dependencies-matrix.outputs.matrix }}
      has-dependencies:
        value: ${{ jobs.dependencies-matrix.outputs.has-dependencies }}
jobs:
  plan:
    runs-on: ubuntu-latest
    steps:
      - run: echo "atmos terraform plan ${{inputs.component}} -s ${{inputs.stack}}"
  apply:
    runs-on: ubuntu-latest
    needs: plan
    environment: ${{ inputs.environment }}
    steps:
      - run: echo "atmos terraform apply ${{inputs.component}} -s ${{inputs.stack}}"
  dependencies-matrix:
    runs-on: ubuntu-latest
    needs:
      - apply
    outputs:
      matrix: ${{ steps.matrix.outputs.matrix }}
      has-dependencies: ${{ steps.matrix.outputs.matrix!='{"include":[]}'}}
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ inputs.ref }}
      - id: matrix
        run: |
          metrix=$(./scripts/deps.pl "${{inputs.stack}}-${{inputs.component}}"| jq -c '{include:[.[]]}')
          echo "matrix=$matrix" >> $GITHUB_OUTPUT
