name: ci-atmos-create-update-deployment-env
run-name: upsert deployment environment
on:
  workflow_call:
    secrets:
      environments_github_token:
        description: A GitHub token with write access to the repository's deployments.
        required: true
    inputs:
      component:
        description: The atmos component to create or update the deployment environment for.
        required: true
        type: string
      stack:
        description: The atmos stack to create or update the deployment environment for.
        required: true
        type: string
      full_stack_name:
        description: The atmos full stack name to create or update the deployment environment for.
        required: true
        type: string
      ref:
        description: The ref to checkout. If not provided, the pull_request head ref is used.
        required: false
        type: string
        default: ${{ github.event.pull_request.head.sha }}
      default-branch:
        description: The default branch to use for the base ref.
        required: false
        type: string
        default: ${{ github.event.repository.default_branch }}
jobs:
  create-update-deployment-env:
    name: create-update-deployment-env
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ inputs.ref }}

      - uses: hashicorp/setup-terraform@v2
      - uses: cloudposse/github-action-setup-atmos@v1.0.0
        with:
          install-wrapper: false

      - name: build payload from atmos
        id: payload
        run: |
          payload=$(atmos describe stacks ${{ inputs.component }} -s ${{ inputs.stack }} --sections=settings --format json| jq -c 'keys[] as $k | .[$k].components.terraform | keys[] as $c | .[$c].settings.github')
          echo "payload=$payload" >> $GITHUB_OUTPUT

      - name: create or update deployment environment
        shell: bash
        run: |
          result=$(curl \
            -o - -I\
            -sS \
            -X PUT \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.environments_github_token }}"\
            -H "X-GitHub-Api-Version: 2022-11-28" \
            "${{github.api_url}}/repos/${{github.repository}}/environments/${{inputs.full_stack_name}}" \
          -d "${{ steps.payload.outputs.payload }}")
          echo "$result" | jq -c '.'
