name: Stack `testing-test-tst` `foo1`
on:
  push:
    branches: [ main ]

permissions:
  contents: write
  id-token: write

jobs:
  do:
    uses: cloudposse/github-actions-workflows-atmos/.github/workflows/stack-deploy.yml@main
    with:
      stack: testing-test-tst
      component: foo1
      environment: testing-test-tst-foo1
