name: Stack testing-test-tst foo1
on:
  workflow_dispatch: {}

permissions:
  deployments: write
  id-token: write
  contents: read

jobs:
  do:
    uses: cloudposse/github-actions-workflows-atmos/.github/workflows/stack-deploy.yml@main
    with:
      stack: testing-test-tst
      component: foo1
      environment: testing-test-tst-foo1
    secrets:
      github-private-actions-pat: ${{ secrets.PUBLIC_REPO_ACCESS_TOKEN }}
